### ISSUE TITLE
Remove GCentral Dependency

### ISSUE THREAD

**Issue by JamesMc86** [LabVIEW-Open-Source/Epoch-Time#2]
Installed this to a project to try it out but was frustrated to see it installs the GCentral menu package.

While this is a worthy cause this then gets sucked in to my project dependencies which I want to keep minimal. It also feels a little invasive to have packages install un-required dependencies.

**Comment by francois-normandin** [comment]
@JamesMc86 thanks for the honest feedback.
I kind of agree with you as I try to avoid pulling the whole OpenG libraries in the core code of the project.
I feel like I didn't follow my own strategy on this.

I'd like an honest answer to the following proposal:
What if the dependency was namespaced in the LVOS palette and didn't show up as a dependency, while still installing the GCentral link? Would you consider it a showstopper still? I'm asking because although I want to propagate awareness for GCentral, I don't want to include anything that is a barrier to adoption of the code, so I'm very sensitive about your request.

**Comment by francois-normandin** [comment]
@JamesMc86 
Here's an updated LVOS palette package without the GCentral dependency:
https://github.com/LabVIEW-Open-Source/LVOS-Palette/releases/tag/1.0.2

It will be released sometime soon on VIPM Community.

**Comment by JamesMc86** [comment]
Thanks @francois-normandin 

To answer your proposal I probably wouldn't have noticed it was there! And I would probably tolerate it.

However it still feels wrong to be. A bit like when you would install "freeware" and it would install avg or some other random software on your system. It breaches my expectations as a user and I personally feel would reflect badly on GCentral

**Comment by francois-normandin** [comment]
And that's another reason for removing it completely... It was a personal initiative, no GCentral's. Since I'm a board member, I can see why there would be further confusion.

Thanks again for pointing the obvious. Good open source is all about having confidence that the code is legit, well maintained, and clean of unwanted side effects. Your analogy to "freeware" is spot on. 

I'll close this issue as soon as the updated package is made public on vipm. And thanks for giving this library a shot! Do let me know if the exposed API feels incomplete to you.

**Comment by francois-normandin** [comment]
LVOS palette update was released a while back. Forgot to close this issue at the time.
