### ISSUE TITLE
Package "Epoch Date & Time" not compatible with LabVIEW 2023 Q3

### ISSUE THREAD

**Issue by Bilsix** [LabVIEW-Open-Source/Epoch-Time#7]
## Quick Information

- **OS:** Windows 10 Pro, 22H2
- **LabVIEW Version:** 2023 Q3

## What Happened?
Everything was working fine with LabVIEW 2020 Q1.
I tried to step up to LabVIEW 2023 Q3 on the same laptop and the same OS, unfortunately this package is not compatible with this new LabVIEW version.

## Steps to reproduce
1. Use LabVIEW 2020.
2. Install Epoch Date & Time via VIPM. It works
3. Deinstall LabVIEW 2020 and install LabVIEW 2023 Q3
4. Install Epoch Date & Time via VIPM. There's a package information in red that mentions : "This package is **not** compatible with your operating system or any LabVIEW version installed on your computer."

## Screenshots
![image](https://github.com/LabVIEW-Open-Source/Epoch-Time/assets/48726070/c3e76e68-d7ca-4fac-9beb-47f910bd7b60)

## Priority/Severity
As you want @francois-normandin ! Je ne suis pas assez bon pour detecter d'où vient le problème !
Peut-être les sources qui n'ont pas été sauvées dans cette version de LabVIEW ?

**Comment by francois-normandin** [comment]
@Bilsix I doubt it is a problem with the package itself. It is very likely a fluke with VIPM.

I'm installing 2023Q3 on my machine to make sure. In the meantime, this package is pure-LabVIEW (no DLLs, dotNet, etc.) and is compiled in LV2013 32-bit, so it will be fully compatible with any 32/64-bit version of LabVIEW on any target.
VIPM instructs LabVIEW to mass compiles when it finishes installing the package, but it does not get to that point.

In the past 3-4 years, I must have seen this issue only once or twice, and could never reproduce it (**)... Apart from uninstalling the package + restarting both LabVIEW and VIPM, I am afraid I cannot offer much more help.

(**) Happened when I was building packages in LV2013 and installing them in LV2019 to verify the integrity of the build. It did not happen on all packages and my building/testing was time-spaced enough I didn't spend time investigating. I don't believe I've seen this happen since I updated to VIPM 2023. though.  Might be worth checking if you have the latest VIPM version?

**Comment by francois-normandin** [comment]
@Bilsix Je confirme que j'ai pu installer Epoch Date & Time sur 2023Q3

![image](https://github.com/LabVIEW-Open-Source/Epoch-Time/assets/11728548/f95c83c7-f5ec-4d13-89fc-e96f1879b84d)

**Comment by Bilsix** [comment]
Hi @francois-normandin
Thanks for your quick answer ! Hmm, good to know the issue comes from my slant and is not epidemic. It means the version 1.0.2.6 is ok and doesn't need to be updated.

Well, I finally found a workaround for the issue here: I copy-pasted manually (I confess, I know that's not elegant) the folder from
National Instruments\**LabVIEW 2020**\vi.lib\LabVIEW Open Source Project
to
National Instruments\**LabVIEW 2023**\vi.lib\LabVIEW Open Source Project

Then I opened my project with LabVIEW 2023, and it was working... :)

Thanks again for your work François !
